$schema: 'https://moonrepo.dev/schemas/tasks.json'

fileGroups:
  rust:
  - 'src/**/*.rs'
  - 'Cargo.toml'
  - 'Cargo.lock'

tasks:
  build:
    command: 'cargo build --release'
    inputs:
    - '@globs(rust)'
    options:
      runInCI: true
  
  dev:
    command: 'cargo run'
    inputs:
    - '@globs(rust)'
    options:
      runInCI: false
      

  test:
    command: 'cargo test'
    inputs:
    - '@globs(rust)'
    options:
      runInCI: true
      